title: "cat-self-update"
description: "cat-self-update"
theme: jekyll-theme-slate
github:
  is_project_page: true
  repository_url: https://github.com/cat2151/cat-self-update
plugins:
  - jekyll-sitemap
